//
// Mini-Project 3 - Game of Life
// Olin Computer Architecture FA25
//
// Given a 24-bit input (8-bit RGB) signal, convert to the raw output
// necessary for a single WS2812B LED.
//
// Author: Carter Harris
module led_control #(
    // Define timing constants
    // WS2812 have a code system for a on/off signal where the input is on and
    // then off for a specified period of time, per their datasheet. The time
    // is converted to FPGA ticks based on the 12MHz clock cycle below.
    //
    // Timings are not quite perfect to the micro-scale specifications of the
    // WS2812B LED, but are within the +/-150ns margin of error. 
    parameter OFF_HIGH_TIME = 5,  // 0.4us
    parameter OFF_LOW_TIME = 10, // 0.85us
    parameter ON_HIGH_TIME = 10, // 0.8us
    parameter ON_LOW_TIME = 5, // 0.45us
    parameter TICKS_PER_CYCLE = ON_HIGH_TIME + ON_LOW_TIME,
    parameter BITS_PER_LED = 24
)
(
    input logic clk,
    input logic [23:0] rgb_input,
    input logic resetting,
    output logic next_led,
    output logic led_signal,
);
    // This first section only deals with creating the on-off code for each
    // individual bit of the LED. Actually assigning to the output based on the
    // input comes next.
    //
    // Create counters
    logic [$clog2(TICKS_PER_CYCLE) - 1:0] current_cycle_count = 0;
    logic [$clog2(BITS_PER_LED)    - 1:0] current_bit = BITS_PER_LED - 1;
    logic on_code_signal;
    logic off_code_signal;

    initial begin
        next_led = 0;
    end
    
    // Count ticks in the current bit cycle
    always_ff @(posedge clk) begin
        // In an entire matrix, the output is overridden to reset to drive the next
        // LED. The matrix controller that resets this module controls in the output
        // in this case, during whcih time the resetting input is high. When this
        // goes low, this code should be in a state as if it was newly initialized.
        // Ensure that behavior here.
        if(resetting) begin
            current_cycle_count <= 0;
            current_bit <= BITS_PER_LED - 1;
            next_led <= 1'b0;
        end
        else if(current_cycle_count == TICKS_PER_CYCLE - 1) begin
            // Increment the counter regardless
            current_cycle_count <= 0;
            // Check if this was the last bit on the current LED
            if (current_bit == 0) begin
                current_bit <= BITS_PER_LED - 1;
                next_led <= 1'b0;
            end
            // If there is only one bit left to transmit, signal this to the
            // calling process so that at the falling edge of this value
            // the next input can be loaded.
            else if (current_bit == 1) begin
                current_bit <= current_bit - 1;
                next_led <= 1'b1;
            end
            // If nothing special, decrement to the next bit in the input
            else begin
                current_bit <= current_bit - 1;
            end
        end
        else begin
            current_cycle_count <= current_cycle_count + 1;
        end
    end

    // Generate the on or off wave based on the length of the on pulse
    // and the current tick of the cycle.
    assign on_code_signal = (current_cycle_count < ON_HIGH_TIME);
    assign off_code_signal = (current_cycle_count < OFF_HIGH_TIME);

    // Now deal with iterating between bits.
    // This module translates from a typical RGB pattern to the GRB pattern
    // required for the WS2812B LED. This still assumes that the 1st bit, 8th
    // bit and so are are the most significant bits of the RGB signal.
    //
    // Based on the input bit, assign the output to either the on or off code
    // signal generated by the timing above. 
    always_comb begin
        if(resetting) begin
            led_signal = 1'b0;
        end
        // Translate first 8 bits red to middle 8 bits for the LED
        else if(current_bit > 15) begin
            led_signal = rgb_input[current_bit - 8] ? on_code_signal : off_code_signal;
        end
        // Translate middle 8 bits green to first 8 bits for the LED
        else if((current_bit <= 15) && (current_bit > 7)) begin
            led_signal = rgb_input[current_bit + 8] ? on_code_signal : off_code_signal;
        end
        // The last 8 bits for both is blue so no shifting needed
        else begin
            led_signal = rgb_input[current_bit] ? on_code_signal : off_code_signal;
        end
    end
endmodule
